version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: stream_postgres
    environment:
      POSTGRES_USER: stream_user
      POSTGRES_PASSWORD: stream_pass
      POSTGRES_DB: stream_db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: stream_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  backend:
    build: ./backend
    container_name: stream_backend
    volumes:
      - ./backend/storage:/app/storage   # store frames in host machine
    environment:
      DB_HOST: postgres
      DB_NAME: stream_db
      DB_USER: stream_user
      DB_PASS: stream_pass
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always

volumes:
  pgdata:
